# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budget_app_development
  username: postgres
  password: <%= Rails.application.credentials.database_password %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: Budget_app_test
  username: postgres
  password: <%= Rails.application.credentials.database_password %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: Budget_app_production
  username: Budget_app
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>
